meta_product_name: "Arthur Thieffry"
meta_title: "Arthur Thieffry - Développement Web Fullstack"
meta_description: "Arthur Thieffry - Développement web fullstack en Ruby on Rails / ReactJS."
meta_image: "https://res.cloudinary.com/arthieffry/image/upload/v1529430142/meta_image_ltpeqj.png"
# twitter_account: "@lewagonlille"


