meta_product_name: "Arthur Thieffry"
meta_title: "Arthur Thieffry - Développement Web Fullstack"
meta_description: "Arthur Thieffry - Développement web fullstack en Ruby on Rails / ReactJS."
meta_image: "logoAT.png" # Une image dans notre dossier app/assets/images/
# twitter_account: "@lewagonlille"


